apiVersion: v1
kind: Pod
metadata:
  name: devops-with-labels
  labels:
    env: prod
    owner: auth-team
  annotations:
    git-info: "commit 93c34fb33f2398cf3308bf42ad7ef0df33dc86d8 Author: Tim Fogarty <tim@tfogo.com> Date: Tue Aug 28 17:42:14 2018 -0700"
spec:
  containers:
    - image: tfogo/devops
      name: devops
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      resources:
        requests:
          cpu: 500m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 256Mi
