apiVersion: v1
kind: Pod
metadata:
  name: devops-with-resources
spec:
  containers:
    - image: tfogo/devops:v1
      name: devops
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      resources:
        requests:
          cpu: 500m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 256Mi
