apiVersion: v1
kind: Pod
metadata:
  name: devops-with-liveness
spec:
  containers:
    - image: tfogo/devops:v1
      name: devops
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
			livenessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
