apiVersion: v1
kind: Pod
metadata:
  name: devops
spec:
  containers:
    - image: tfogo/devops
      name: devops
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
